### ISSUE TITLE
Is this supposed to work on iOS too?

### ISSUE THREAD

**Issue by awhitford** [danieldai/android_metadata#1]
The README does not say that this is Android only, so I assume that it should work with iOS too.  However, I get the following stack trace:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method getMetaDataAsMap on channel plugins.mianjiajia.com/android_metadata)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
#2      AndroidMetadata.metaDataAsMap (package:android_metadata/android_metadata.dart:11:24)
#3      _HomeScreenState._buildHomeStatus.<anonymous closure> (package:myapp/screens/home_screen.dart:230:45)
#4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
#5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
#8      BaseTapGestureRecognizer.<…>
```

Can you please clarify if this is supposed to function OK with iOS?

**Comment by danieldai** [comment]
Sorry about that. But it only on Android, at least for now.
