### ISSUE TITLE
In the AndroidManifest.xml, Obtain the meta-data value may be integer type

### ISSUE THREAD

**Issue by zhbh** [danieldai/android_metadata#3]
In the flutter project, there has `<meta-data android:name="flutterEmbedding" android:value="2" />` in the AndroidManifest.xml, which cause the exception as fellows.

I think it happened because it received the value of flutterEmbedding of meta-data that was an integer, not String.

Suggest that it not only gets String but also other basis types(integer).  Or all convert String type when it generates.
``` 
java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
W/Bundle  ( 1425):      at android.os.BaseBundle.getString(BaseBundle.java:1199)
W/Bundle  ( 1425):      at com.mianjiajia.android_metadata.AndroidMetadataPlugin.onMethodCall(AndroidMetadataPlugin.java:50)
W/Bundle  ( 1425):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:226)
W/Bundle  ( 1425):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/Bundle  ( 1425):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:631)
W/Bundle  ( 1425):      at android.os.MessageQueue.nativePollOnce(Native Method)
W/Bundle  ( 1425):      at android.os.MessageQueue.next(MessageQueue.java:335)
W/Bundle  ( 1425):      at android.os.Looper.loop(Looper.java:183)
W/Bundle  ( 1425):      at android.app.ActivityThread.main(ActivityThread.java:7523)
W/Bundle  ( 1425):      at java.lang.reflect.Method.invoke(Native Method)
W/Bundle  ( 1425):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
W/Bundle  ( 1425):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
I/flutter ( 1425): {flutterEmbedding: null}
```

**Comment by danieldai** [comment]
Good points. I will handle it. and PR is also welcome

**Comment by SamuelHaws** [comment]
@zhbh See https://github.com/danieldai/android_metadata/pull/4 for a fix.

**Comment by danieldai** [comment]
Bug fixed
